# Use postgres/example user/password credentials
version: '3.5'

networks: 
    postgres-compose-network:
        driver: bridge

services:    
    
    app:
        build: .
        image: app
        ports:
            - "5000:5000"
        networks:
            - postgres-compose-network
        depends_on:
            - db

    rabbitmq:
        image: rabbitmq:3-management
        ports:
            - 5672:5672
            - 15672:15672
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
            - RABBITMQ_USER=guest
            - RABBITMQ_PASSWORD=guest
        volumes:
            - ./tmp/rabbitmq/data/:/var/lib/rabbitmq/
            - ./tmp/rabbitmq/log/:/var/log/rabbitmq
        networks:
            - postgres-compose-network

    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: sigo
        restart: always
        ports:
            - "5432:5432"
        networks:
            - postgres-compose-network

    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: "furtado.danilo@gmail.com"
            PGADMIN_DEFAULT_PASSWORD: "PgAdmin"
            PGADMIN_LISTEN_PORT: 80
        ports:
            - "5674:80"
        depends_on:
            - db
        networks:
            - postgres-compose-network